In [3]:
import pandas as pd

df = pd.read_csv("../src/data/data_clean.csv")

In [6]:
from mlxtend.frequent_patterns import apriori, association_rules

keywords = ["staff", "location", "room", "clean", "service", "wifi"]

data = []
for r in df["clean"]:
    row = {k: (k in r) for k in keywords}
    data.append(row)

df_bin = pd.DataFrame(data)

freq = apriori(df_bin, min_support=0.02, use_colnames=True)
rules = association_rules(freq, metric="confidence", min_threshold=0.5)

rules.sort_values("lift", ascending=False).head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
6,"(staff, room)",(clean),0.155393,0.276784,0.081086,0.521809,1.885255,1.0,0.038075,1.512400,0.555960,0.230953,0.338799,0.407383
5,"(clean, staff)",(room),0.107305,0.498061,0.081086,0.755654,1.517190,1.0,0.027641,2.054210,0.381863,0.154661,0.513195,0.459228
2,(clean),(room),0.276784,0.498061,0.204457,0.738688,1.483126,1.0,0.066602,1.920839,0.450417,0.358453,0.479394,0.574597
7,"(location, clean)",(room),0.037070,0.498061,0.027224,0.734387,1.474490,1.0,0.008761,1.889735,0.334188,0.053600,0.470825,0.394523
4,"(location, staff)",(room),0.044155,0.498061,0.026359,0.596968,1.198583,1.0,0.004367,1.245406,0.173335,0.051098,0.197049,0.324946

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=3000)

df = df.dropna(subset=["clean"])

X = vectorizer.fit_transform(df["clean"])

In [7]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=42)
df["cluster"] = kmeans.fit_predict(X)

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=3000)

X = vectorizer.fit_transform(df["clean"])

In [8]:
df[["clean", "cluster"]].head(10)

                                               clean  cluster
0  pleasant  min walk along the sea front to the ...        4
1  really lovely hotel stayed on the very top flo...        1
2  ett mycket bra hotell det som drog ner betyget...        0
3  we stayed here for four nights in october the ...        2
4  we stayed here for four nights in october the ...        2
5  we loved staying on the island of lido you nee...        3
6  lovely view out onto the lagoon excellent view...        0
7  ottimo soggiorno e ottima sistemazione nei gio...        0
8  gnstiger ausgangspunkt fr venedig besuche ruhi...        0
9  lidoen er perfekt til et par dages ro og afsla...        0